# Generated by Django 2.2 on 2019-04-07 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Subcounty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcounty', models.CharField(max_length=150)),
                ('parish', models.CharField(max_length=150)),
                ('village', models.CharField(max_length=200)),
                ('source_csv', models.CharField(max_length=500)),
                ('district', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='pride.District')),
            ],
        ),
    ]
