# Generated by Django 2.2 on 2019-04-07 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pride', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parish', models.CharField(max_length=150)),
            ],
        ),
        migrations.RemoveField(
            model_name='subcounty',
            name='parish',
        ),
        migrations.RemoveField(
            model_name='subcounty',
            name='source_csv',
        ),
        migrations.RemoveField(
            model_name='subcounty',
            name='village',
        ),
        migrations.AlterField(
            model_name='district',
            name='district',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='subcounty',
            name='subcounty',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('village', models.CharField(max_length=200)),
                ('parish', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='pride.Parish')),
            ],
        ),
        migrations.AddField(
            model_name='parish',
            name='subcounty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='pride.Subcounty'),
        ),
    ]
