# Generated by Django 2.2 on 2019-04-07 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pride', '0002_auto_20190407_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='district',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='subcounty',
            name='subcounty',
            field=models.CharField(max_length=150),
        ),
    ]
