# Generated by Django 2.2 on 2019-04-08 09:44

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('pride', '0003_auto_20190407_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=20)),
                ('birth_year', models.DateField()),
                ('username', models.CharField(max_length=200)),
                ('marriage', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=100)),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('profile_photo', models.FileField(upload_to='')),
                ('community_status', models.CharField(max_length=150)),
                ('instructor_possibility', models.BooleanField()),
                ('farm_area', models.CharField(max_length=100)),
                ('crop_type', models.CharField(max_length=100)),
                ('district_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pride.District')),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pride.Parish')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=200)),
                ('area_acres', models.FloatField()),
                ('harvest_kgs', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rice_type', models.CharField(max_length=100)),
                ('sowing_date', models.DateField()),
                ('sowing_type', models.CharField(max_length=100)),
                ('planting_type', models.CharField(max_length=100)),
                ('levelling', models.CharField(max_length=100)),
                ('ridge', models.CharField(max_length=100)),
                ('watercourse_state', models.CharField(max_length=100)),
                ('fertilizer', models.BooleanField()),
                ('fertilizer_1_type', models.CharField(max_length=100)),
                ('fertilizer_1_amount', models.IntegerField()),
                ('fertilizer_2_type', models.CharField(max_length=100)),
                ('fertilizer_2_amount', models.IntegerField()),
                ('weed_condition', models.CharField(max_length=100)),
                ('total_weed_times', models.IntegerField()),
                ('harvest_date', models.DateField()),
                ('note', models.CharField(max_length=500)),
                ('photo1', models.FileField(upload_to='')),
                ('photo2', models.FileField(upload_to='')),
                ('photo3', models.FileField(upload_to='')),
                ('photo4', models.FileField(upload_to='')),
                ('farm_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pride.Farmer')),
                ('harvest_amount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pride.Season')),
            ],
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('LoginID', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=200)),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('district_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pride.District')),
                ('subcounty_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pride.Subcounty')),
            ],
        ),
        migrations.AddField(
            model_name='farmer',
            name='past_harvests',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pride.Season'),
        ),
        migrations.AddField(
            model_name='farmer',
            name='subcounty_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pride.Subcounty'),
        ),
        migrations.AddField(
            model_name='farmer',
            name='village',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pride.Village'),
        ),
    ]
