# Generated by Django 2.2 on 2019-04-16 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pride', '0004_auto_20190408_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='community_status',
            field=models.CharField(choices=[('mob', 'Mobilizer'), ('other', 'Other')], max_length=25),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='crop_type',
            field=models.CharField(choices=[('rice', 'Rice'), ('pot', 'Potato'), ('maiz', 'Maize')], max_length=25),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='farm_area',
            field=models.CharField(choices=[('1', '1-5ac'), ('2', '5-10ac'), ('3', '10-15ac'), ('4', '15-20ac'), ('5', 'Other')], max_length=25),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=20),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='instructor_possibility',
            field=models.BooleanField(choices=[('y', 'Yes'), ('n', 'No')]),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='language',
            field=models.CharField(choices=[('english', 'English'), ('luganda', 'Luganda'), ('other', 'Other')], max_length=25),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='marriage',
            field=models.CharField(choices=[('married', 'Married'), ('single', 'Single'), ('divorced', 'Divorced')], max_length=25),
        ),
    ]
