# Generated by Django 2.2 on 2019-04-16 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pride', '0005_auto_20190416_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='village',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Village',
        ),
    ]
