# Generated by Django 2.2 on 2019-04-16 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pride', '0006_auto_20190417_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='village',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
