# Generated by Django 2.2 on 2019-04-16 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pride', '0007_auto_20190417_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='instructor_possibility',
            field=models.BooleanField(choices=[(1, 'Yes'), (0, 'No')]),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='past_harvests',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='pride.Season'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='profile_photo',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='village',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
