# Generated by Django 2.2 on 2019-04-18 05:26

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('pride', '0008_auto_20190417_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='farm_area',
            field=models.CharField(choices=[('1', '0-5ac'), ('2', '5-10ac'), ('3', '10-15ac'), ('4', '15-20ac'), ('5', 'Other')], max_length=25),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='past_harvests',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='pride.Season'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Contact phone number', max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='profile_photo',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('village', models.CharField(max_length=200, null=True)),
                ('parish', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='pride.Parish')),
            ],
        ),
    ]
