# Generated by Django 2.2 on 2019-04-18 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pride', '0009_auto_20190418_0826'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmer',
            old_name='Officer',
            new_name='officer',
        ),
    ]
