# Generated by Django 2.2 on 2019-04-18 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pride', '0010_auto_20190418_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='profile_photo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
